import { createStore } from "vuex";

export default createStore({
  state: {
    Element_table: [
      {
        1: { name: "H", id: "1" },
        2: { name: "He", id: "2" }
      },
      {
        1: { name: "Li", id: "3" },
        2: { name: "Be", id: "4" },
        3: { name: "", id: "" },
        4: { name: "", id: "" },
        5: { name: "", id: "" },
        6: { name: "", id: "" },
        7: { name: "", id: "" },
        8: { name: "", id: "" },
        9: { name: "", id: "" },
        10: { name: "", id: "" },
        11: { name: "", id: "" },
        12: { name: "", id: "" },
        13: { name: "B", id: "5" },
        14: { name: "C", id: "6" },
        15: { name: "N", id: "7" },
        16: { name: "O", id: "8" },
        17: { name: "F", id: "9" },
        18: { name: "Ne", id: "10" }
      },
      {
        1: { name: "Na", id: "11" },
        2: { name: "Mg", id: "12" },
        3: { name: "", id: "" },
        4: { name: "", id: "" },
        5: { name: "", id: "" },
        6: { name: "", id: "" },
        7: { name: "", id: "" },
        8: { name: "", id: "" },
        9: { name: "", id: "" },
        10: { name: "", id: "" },
        11: { name: "", id: "" },
        12: { name: "", id: "" },
        13: { name: "Al", id: "13" },
        14: { name: "Si", id: "14" },
        15: { name: "P", id: "15" },
        16: { name: "S", id: "16" },
        17: { name: "Cl", id: "17" },
        18: { name: "Ar", id: "18" }
      },
      {
        19: "K",
        20: "Ca",
        21: "Sc",
        22: "Ti",
        23: "V",
        24: "Cr",
        25: "Mn",
        26: "Fe",
        27: "Co",
        28: "Ni",
        29: "Cu",
        30: "Zn",
        31: "Ga",
        32: "Ge",
        33: "As",
        34: "Se",
        35: "Br",
        36: "Kr"
      },
      {
        37: "Rb",
        38: "Sr",
        39: "Y",
        40: "Zr",
        41: "Nb",
        42: "Mo",
        43: "Tc",
        44: "Ru",
        45: "Rh",
        46: "Pd",
        47: "Ag",
        48: "Cd",
        49: "In",
        50: "Sn",
        51: "Sb",
        52: "Te",
        53: "I",
        54: "Xe"
      },
      {
        55: "Cs",
        56: "Ba",
        57: "La-Lu",
        72: "Hf",
        73: "Ta",
        74: "W",
        75: "Re",
        76: "Os",
        77: "Ir",
        78: "Pt",
        79: "Au",
        80: "Hg",
        81: "Tl",
        82: "Pb",
        83: "Bi",
        84: "Po",
        85: "At",
        86: "Rn"
      },
      {
        87: "Fr",
        88: "Ra",
        89: "Ac-Lr",
        104: "Rf",
        105: "Db",
        106: "Sg",
        107: "Bh",
        108: "Hs",
        109: "Mt",
        110: "Ds",
        111: "Rg",
        112: "Cn",
        113: "Uut",
        114: "Uuq",
        115: "Uup",
        116: "Uuh",
        117: "Uus",
        118: "Uuo"
      },
      {
        1: { name: "", id: "" },
        2: { name: "", id: "" },
        3: { name: "La", id: "57" },
        4: { name: "Ce", id: "58" },
        5: { name: "Pr", id: "59" },
        6: { name: "Nd", id: "60" },
        7: { name: "Pm", id: "61" },
        8: { name: "Sm", id: "62" },
        9: { name: "Eu", id: "63" },
        10: { name: "Gd", id: "64" },
        11: { name: "Tb", id: "65" },
        12: { name: "Dy", id: "66" },
        13: { name: "Ho", id: "67" },
        14: { name: "Er", id: "68" },
        15: { name: "Tm", id: "69" },
        16: { name: "Yb", id: "70" },
        17: { name: "Lu", id: "71" },
        18: { name: "", id: "" }
      },
      {
        1: { name: "", id: "" },
        2: { name: "", id: "" },
        3: { name: "Ac", id: "89" },
        4: { name: "Th", id: "90" },
        5: { name: "Pa", id: "91" },
        6: { name: "U", id: "92" },
        7: { name: "Np", id: "93" },
        8: { name: "Pu", id: "94" },
        9: { name: "Am", id: "95" },
        10: { name: "Cm", id: "96" },
        11: { name: "Bk", id: "97" },
        12: { name: "Cf", id: "98" },
        13: { name: "Es", id: "99" },
        14: { name: "Fm", id: "100" },
        15: { name: "Md", id: "101" },
        16: { name: "No", id: "102" },
        17: { name: "Lr", id: "103" },
        18: { name: "", id: "" }
      }
    ]
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {}
});
